displayName: Widgets
description: !include widget.md
/table-widget:
    description: !include table-widget.md
/help-widget:
    description: !include help-widget.md
/link-objects-widgets:
    description: !include link-objects-widget.md
/notes-widgets:
    description: !include notes-widget.md