displayName: Components
description: "Base components for KIX18 user interface."
/widgets: !include widgets/index.raml
/action: 
    description: !include action.md
/action-list: 
    description: !include action-list.md
/editor: 
    description: !include editor.md
/file-entry: 
    description: !include file-entry.md
/filter: 
    description: !include filter.md
/main-form: 
    description: !include main-form.md
/label-list: 
    description: !include label-list.md
/label-value-group: 
    description: !include label-value-group.md
/link-target: 
    description: !include link-target.md
/loading-shield: 
    description: !include loading-shield.md
/loading-spinner: 
    description: !include loading-spinner.md
/object-details-page: 
    description: !include object-details-page.md
/object-property-label: 
    description: !include object-property-label.md
/router-outlet: 
    description: !include router-outlet.md
/standard-table: 
    description: !include standard-table.md
/tab-container: 
    description: !include tab-container.md
/table-tree: 
    description: !include table-tree.md
/timer: 
    description: !include timer.md
/translation-string: 
    description: !include translation-string.md
/tree: 
    description: !include tree.md
/widget-container: 
    description: !include widget-container.md