export enum PersonalSettingsAction {

    PERSONAL_SETTINGS_INITIALIZE = "PERSONAL_SETTINGS_INITIALIZE",

    LOAD_PERSONAL_SETTINGS = "LOAD_PERSONAL_SETTINGS",

    PERSONAL_SETTINGS_LOADED = "PERSONAL_SETTINGS_LOADED"

}
