export enum LoginAction {

    LOGIN_ERROR = 'LOGIN_ERROR',

    LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED',

    LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED',

    LOGIN_VALIDATE = 'LOGIN_VALIDATE',

    LOGIN_CONNECT = 'LOGIN_CONNECT',

    LOGIN_AUTH = 'LOGIN_AUTH'

}
