export enum AgentEvent {

    GET_PERSONAL_SETTINGS = "GET_PERSONAL_SETTINGS",

    GET_PERSONAL_SETTINGS_FINISHED = "GET_PERSONAL_SETTINGS_FINISHED",

    GET_PERSONAL_SETTINGS_ERROR = "GET_PERSONAL_SETTINGS_ERROR",

    SET_PREFERENCES = "SET_PREFERENCES",

    SET_PREFERENCES_FINISHED = "SET_PREFERENCES_FINISHED",

    SET_PREFERENCES_ERROR = "SET_PREFERENCES_ERROR",

    GET_CURRENT_USER = "GET_CURRENT_USER",

    GET_CURRENT_USER_FINISHED = "GET_CURRENT_USER_FINISHED",

    GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",

}
