export enum KixSidebarAction {

    KIX_SIDEBAR_INITIALIZE = "KIX_SIDEBAR_INITIALIZE",

    KIX_SIDEBAR_CONFIGURATION_LOADED = "KIX_SIDEBAR_CONFIGURATION_LOADED",

    KIX_SIDEBAR_ERROR = "KIX_SIDEBAR_ERROR"

}
