/**
 * Copyright (C) 2006-2024 KIX Service Software GmbH, https://www.kixdesk.com
 * --
 * This software comes with ABSOLUTELY NO WARRANTY. For details, see
 * the enclosed file LICENSE for license information (GPL3). If you
 * did not receive this file, see https://www.gnu.org/licenses/gpl-3.0.txt.
 * --
 */

export enum ObjectFormEvent {

    OBJECT_FORM_HANDLER_CHANGED = 'OBJECT_FORM_HANDLER_CHANGED',

    FIELD_ORDER_CHANGED = 'FIELD_ORDER_CHANGED',

    OBJECT_FORM_VALUE_MAPPER_INITIALIZED = 'OBJECT_FORM_VALUE_MAPPER_INITIALIZED',

    OBJECT_FORM_VALUE_CHANGED = 'OBJECT_FORM_VALUE_CHANGED',

    SCROLL_TO_FORM_VALUE = 'SCROLL_TO_FORM_VALUE',

    BLOCK_FORM = 'BLOCK_FORM',

    FORM_VALUE_ADDED = 'FORM_VALUE_ADDED',

    FORM_SUBMIT_ENABLED = 'FORM_SUBMIT_ENABLED',

    PAGE_ADDED = 'PAGE_ADDED',

    PAGE_CHANGED = 'PAGE_CHANGED',

    PAGE_UPDATED = 'PAGE_UPDATED',

    PAGE_DELETED = 'PAGE_DELETED',

    EDIT_GROUP = 'EDIT_GROUP',

    GROUP_ADDED = 'GROUP_ADDED',

    GROUP_UPDATED = 'GROUP_UPDATED',

    GROUP_DELETED = 'GROUP_DELETED',

    ADD_FIELD = 'ADD_FIELD',

    FIELD_ADDED = 'FIELD_ADDED',

    EDIT_FIELD = 'EDIT_FIELD',

    FIELD_REINITIALIZED = 'FIELD_REINITIALIZED',

    FIELD_DELETED = 'FIELD_DELETED'

}