export enum TicketAction {

    TICKET_INITIALIZE = "DASHBOARD_INITIALIZE",

    TICKET_LOAD_CONTAINER_CONFIG = "DASHBOARD_LOAD_CONTAINER_CONFIG",

    TICKET_CONTAINER_CONFIGURATION_LOADED = "DASHBOARD_CONTAINER_CONFIGURATION_LOADED"

}
