/**
 * Copyright (C) 2006-2024 KIX Service Software GmbH, https://www.kixdesk.com
 * --
 * This software comes with ABSOLUTELY NO WARRANTY. For details, see
 * the enclosed file LICENSE for license information (GPL3). If you
 * did not receive this file, see https://www.gnu.org/licenses/gpl-3.0.txt.
 * --
 */

export enum ContextEvent {

    LOAD_CONTEXT_CONFIGURATION = 'load-context',
    CONTEXT_CONFIGURATION_LOADED = 'context-loaded',

    LOAD_CONTEXT_CONFIGURATIONS = 'LOAD_CONTEXT_CONFIGURATIONS',
    CONTEXT_CONFIGURATIONS_LOADED = 'CONTEXT_CONFIGURATIONS_LOADED',

    REBUILD_CONFIG = 'REBUILD_CONFIG',
    REBUILD_CONFIG_FINISHED = 'REBUILD_CONFIG_FINISHED',

    LOAD_STORED_CONTEXTS = 'LOAD_STORED_CONTEXTS',
    LOAD_STORED_CONTEXTS_FINISCHED = 'LOAD_STORED_CONTEXTS_FINISCHED',

    STORE_CONTEXT = 'STORE_CONTEXT',
    STORE_CONTEXT_FINISCHED = 'STORE_CONTEXT_FINISCHED',

    REMOVE_STORED_CONTEXT = 'REMOVE_STORED_CONTEXT',
    REMOVE_STORED_CONTEXT_FINISHED = 'REMOVE_STORED_CONTEXT_FINISHED',

}
