export enum ContactEvent {

    LOAD_CONTACTS = 'LOAD_CONTACTS',
    CONTACTS_LOADED = 'CONTACTS_LOADED',

    CREATE_CONTACT = 'CREATE_CONTACT',
    CREATE_CONTACT_FINISHED = 'CREATE_CONTACT_FINISHED',
    CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR'

}
