export enum TicketCreationDialogAction {

    CREATE_TICKET = "CREATE_TICKET",

    RESET_TICKET_CREATION = "RESET_TICKET_CREATION",

    LOAD_TICKET_TEMPLATES = "LOAD_TICKET_TEMPLATES",

    CUSTOMER_ID_CHANGED = "CUSTOMER_ID_CHANGED",

    CUSTOMER_CHANGED = "CUSTOMER_CHANGED",

    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED",

    DYNAMIC_FIELD_CHANGED = "DYNAMIC_FIELD_CHANGED",

    PENDING_TIME_CHANGED = "PENDING_TIME_CHANGED",

    PRIORITY_ID_CHANGED = "PRIORITY_ID_CHANGED",

    QUEUE_ID_CHANGED = "QUEUE_ID_CHANGED",

    STATE_ID_CHANGED = "STATE_ID_CHANGED",

    SUBJECT_CHANGED = "SUBJECT_CHANGED",

    TEMPLATE_CHANGED = "TEMPLATE_CHANGED",

    TYPE_ID_CHANGED = "TYPE_ID_CHANGED",

    USER_ID_CHANGED = "USER_ID_CHANGED"

}
