export enum TicketCreationDialogAction {

    CREATE_TICKET = "CREATE_TICKET",

    RESET_TICKET_CREATION = "RESET_TICKET_CREATION",

    LOAD_TICKET_TEMPLATES = "LOAD_TICKET_TEMPLATES",

    SUBJECT_CHANGED = "SUBJECT_CHANGED"

}
