#%RAML 1.0
title: KIX 18 - Frontend

documentation:
  - title: Intruduction
    content: !include descriptions/intruduction.md

/extensions: !include extensions/index.raml
/socket namespaces: !include socket-namespaces/index.raml
/components: !include components/index.raml
