#%RAML 1.0
title: KIX - Frontend Server

documentation:
  - title: Agent Portal
    content: !include descriptions/agent-portal.md
  - title: Modularization - Plugins
    content: !include descriptions/plugins.md
  - title: Build - Webapp
    content: !include descriptions/build-webapp.md
  - title: UI Components
    content: !include descriptions/components.md
  - title: Context
    content: !include descriptions/context.md
  - title: Configuration
    content: !include descriptions/configuration.md
  - title: Context Configuration
    content: !include descriptions/context-configuration.md
  - title: Form Configuration
    content: !include descriptions/form-configuration.md
  - title: ExtendedKIXObjectService
    content: !include extensions/ExtendedKIXObjectService.md
  - title: KIXObjectFactory
    content: !include extensions/KIXObjectFactory.md
  - title: ExtendedLabelProvider
    content: !include extensions/ExtendedLabelProvider.md
  - title: ExtendedTableFactory
    content: !include extensions/ExtendedTableFactory.md
  - title: ExtendedDynamicFormManager
    content: !include extensions/ExtendedDynamicFormManager.md
  - title: ExtendedConfigItemFormFactory
    content: !include extensions/ExtendedConfigItemFormFactory.md
  - title: ExtendedKIXObjectService
    content: !include extensions/ExtendedKIXObjectService.md
  - title: ExtendedDynamicFieldFormUtil
    content: !include extensions/ExtendedDynamicFieldFormUtil.md
  - title: ExtendedDynamicFieldPlaceHolderHandler
    content: !include extensions/ExtendedDynamicFieldPlaceHolderHandler.md
  - title: ExtendedJobFormManager
    content: !include extensions/ExtendedJobFormManager.md

# Extensions
/kix-modules: !include extensions/kix-modules.raml
/kix-configuration: !include extensions/kix-configuration.raml
/components: !include components/index.raml