export enum TableEvent {

    TABLE_INITIALIZED = 'TABLE_INITIALIZED',

    TABLE_READY = 'TABLE_READY',

    REFRESH = 'REFRESH',

    RERENDER_TABLE = 'RERENDER_TABLE',

    SORTED = 'SORTED',

    SCROLL_TO_AND_TOGGLE_ROW = 'SCROLL_TO_AND_TOGGLE_ROW',

    COLUMN_FILTERED = 'COLUMN_FILTERED',

    COLUMN_RESIZED = 'COLUMN_RESIZED',

    ROW_SELECTION_CHANGED = 'ROW_SELECTION_CHANGED',

    ROW_SELECTABLE_CHANGED = 'ROW_SELECTABLE_CHANGED',

    ROW_TOGGLED = 'ROW_TOGGLED',

    ROW_VALUE_STATE_CHANGED = 'ROW_VALUE_STATE_CHANGED',

    ROW_VALUE_CHANGED = 'ROW_VALUE_CHANGED'

}
