export enum TableEvent {

    REFRESH = 'REFRESH',

    SELECTION_CHANGED = 'SELECTION_CHANGED',

    SORTED = 'SORTED',

    TABLE_READY = 'TABLE_READY',

    COLUMN_FILTERED = 'COLUMN_FILTERED',

    COLUMN_RESIZED = 'COLUMN_RESIZED',

    ROW_TOGGLED = 'ROW_TOGGLED',

    TABLE_INITIALIZED = 'TABLE_INITIALIZED',

    RERENDER_TABLE = 'RERENDER_TABLE',

    SCROLL_AND_TOGGLE_TO_OBJECT_ID = 'SCROLL_AND_TOGGLE_TO_OBJECT_ID'

}
