export enum OverlayType {

    HINT = 'HINT',

    WARNING = 'WARNING',

    INFO = 'INFO',

    SUCCESS_TOAST = 'SUCCESS_TOAST',

    HINT_TOAST = 'HINT_TOAST',

    CONTENT_OVERLAY = 'CONTENT_OVERLAY',

    CONFIRM = 'CONFIRM',

    TABLE_COLUMN_FILTER = 'TABLE_COLUMN_FILTER'

}
