export enum CreationDialogAction {

    CREATION_DIALOG_INITIALIZE = "CREATION_DIALOG_INITIALIZE",

    LOAD_CREATION_DIALOG = "LOAD_CREATION_DIALOG",

    CREATION_DIALOG_LOADED = "CREATION_DIALOG_LOADED"

}
