export enum TicketAction {

    TICKET_INITIALIZE = "TICKET_INITIALIZE",

    TICKET_LOAD_CONTAINER_CONFIG = "TICKET_LOAD_CONTAINER_CONFIG",

    TICKET_CONTAINER_CONFIGURATION_LOADED = "TICKET_CONTAINER_CONFIGURATION_LOADED"

}
