export enum ObjectReferenceOptions {

    OBJECT = 'OBJECT',

    AUTOCOMPLETE = 'AUTOCOMPLETE',

    MULTISELECT = 'MULTISELECT',

    LOADINGOPTIONS = 'LOADINGOPTIONS',

    AS_STRUCTURE = 'AS_STRUCTURE'

}
