export enum TicketEvent {

    CREATE_TICKET = 'CREATE_TICKET',
    CREATE_TICKET_FINISHED = 'CREATE_TICKET_FINISHED',
    CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR',

    LOAD_TICKETS = 'LOAD_TICKETS',
    LOAD_TICKETS_FINISHED = 'LOAD_TICKETS_FINISHED',

    LOAD_TICKET = 'LOAD_TICKET',
    LOAD_TICKET_ERROR = 'LOAD_TICKET_ERROR',
    TICKET_LOADED = 'TICKET_LOADED',

    REMOVE_ARTICLE_SEEN_FLAG = 'REMOVE_ARTICLE_SEEN_FLAG',
    REMOVE_ARTICLE_SEEN_FLAG_DONE = 'REMOVE_ARTICLE_SEEN_FLAG_DONE',

    LOAD_ARTICLE_ATTACHMENT = 'LOAD_ARTICLE_ATTACHMENT',
    LOAD_ARTICLE_ATTACHMENT_ERROR = 'LOAD_ARTICLE_ATTACHMENT_ERROR',
    ARTICLE_ATTACHMENT_LOADED = 'ARTICLE_ATTACHMENT_LOADED',

    LOAD_ARTICLE_ZIP_ATTACHMENT = 'LOAD_ARTICLE_ZIP_ATTACHMENT',
    LOAD_ARTICLE_ZIP_ATTACHMENT_ERROR = 'LOAD_ARTICLE_ZIP_ATTACHMENT_ERROR',
    ARTICLE_ZIP_ATTACHMENT_LOADED = 'ARTICLE_ZIP_ATTACHMENT_LOADED',
}
