export enum LoginAction {

    LOGIN_INITIALIZE = 'LOGIN_INITIALIZE',

    LOGIN_ERROR = 'LOGIN_ERROR',

    LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED',

    LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED',

    LOGIN_VALIDATE = 'LOGIN_VALIDATE',

    LOGIN_AUTH = 'LOGIN_AUTH',

    TRANSLATIONS_LOADED = 'TRANSLATIONS_LOADED'

}
