displayName: Extensions
description: !include description.md
/kix-socket-namespace: 
    description: !include kix-socket-namespace.md
/kix-main-menu: 
    description: !include kix-main-menu.md
/kix-configuration: 
    description: !include kix-configuration.md
/kix-modules: 
    description: !include kix-modules.md
/kix-admin-modules: 
    description: !include kix-admin-module.md