export enum TicketEvent {

    REMOVE_ARTICLE_SEEN_FLAG = 'REMOVE_ARTICLE_SEEN_FLAG',
    REMOVE_ARTICLE_SEEN_FLAG_DONE = 'REMOVE_ARTICLE_SEEN_FLAG_DONE',

    LOAD_ARTICLE_ATTACHMENT = 'LOAD_ARTICLE_ATTACHMENT',
    ARTICLE_ATTACHMENT_LOADED = 'ARTICLE_ATTACHMENT_LOADED',

    LOAD_ARTICLE_ZIP_ATTACHMENT = 'LOAD_ARTICLE_ZIP_ATTACHMENT',
    ARTICLE_ZIP_ATTACHMENT_LOADED = 'ARTICLE_ZIP_ATTACHMENT_LOADED'

}
