export enum KIXModulesEvent {

    LOAD_MODULES = 'LOAD_MODULES',

    LOAD_MODULES_FINISHED = 'LOAD_MODULES_FINISHED',

    LOAD_MODULES_ERROR = 'LOAD_MODULES_ERROR',

    LOAD_FORM_CONFIGURATIONS = 'LOAD_FORM_CONFIGURATIONS',

    LOAD_FORM_CONFIGURATIONS_FINISHED = 'LOAD_FORM_CONFIGURATIONS_FINISHED',

    LOAD_FORM_CONFIGURATIONS_ERROR = 'LOAD_FORM_CONFIGURATIONS_ERROR'

}
