export enum KIXModulesEvent {

    LOAD_MODULES = 'LOAD_MODULES',
    LOAD_MODULES_FINISHED = 'LOAD_MODULES_FINISHED',
    LOAD_MODULES_ERROR = 'LOAD_MODULES_ERROR',

    LOAD_BOOKMARKS = 'LOAD_BOOKMARKS',
    LOAD_BOOKMARKS_FINISHED = 'LOAD_BOOKMARKS_FINISHED',
    LOAD_BOOKMARKS_ERROR = 'LOAD_BOOKMARKS_ERROR',

    LOAD_RELEASE_INFO = 'LOAD_RELEASE_INFO',
    LOAD_RELEASE_INFO_FINISHED = 'LOAD_RELEASE_INFO_FINISHED',
    LOAD_RELEASE_INFO_ERROR = 'LOAD_RELEASE_INFO_ERROR',

    LOAD_OBJECT_DEFINITIONS = 'LOAD_OBJECT_DEFINITIONS',
    LOAD_OBJECT_DEFINITIONS_FINISHED = 'LOAD_OBJECT_DEFINITIONS_FINISHED',
    LOAD_OBJECT_DEFINITIONS_ERROR = 'LOAD_OBJECT_DEFINITIONS_ERROR',

    LOAD_FORM_CONFIGURATIONS = 'LOAD_FORM_CONFIGURATIONS',
    LOAD_FORM_CONFIGURATIONS_FINISHED = 'LOAD_FORM_CONFIGURATIONS_FINISHED',
    LOAD_FORM_CONFIGURATIONS_ERROR = 'LOAD_FORM_CONFIGURATIONS_ERROR'

}
