export enum CMDBAction {

    CMDB_INITIALIZE = "CMDB_INITIALIZE",

    CMDB_LOAD_CONTAINER_CONFIG = "CMDB_LOAD_CONTAINER_CONFIG",

    CMDB_CONTAINER_CONFIGURATION_LOADED = "CMDB_CONTAINER_CONFIGURATION_LOADED"

}
