export enum UserListAction {

    USER_LIST_INITIALIZE = "USER_LIST_INITIALIZE",

    USER_LIST_USERS_LOADED = "USER_LIST_USERS_LOADED",

    USER_LIST_CONFIGURATION_LOADED = "USER_LIST_CONFIGURATION_LOADED",

    USER_LIST_ERROR = "USER_LIST_ERROR"

}
