export enum KIXObjectEvent {

    LOAD_OBJECTS = 'LOAD_OBJECTS',
    LOAD_OBJECTS_FINISHED = 'LOAD_OBJECTS_FINISHED',
    LOAD_OBJECTS_ERROR = 'LOAD_OBJECTS_ERROR',

    CREATE_OBJECT = 'CREATE_OBJECT',
    CREATE_OBJECT_FINISHED = 'CREATE_OBJECT_FINISHED',
    CREATE_OBJECT_ERROR = 'CREATE_OBJECT_ERROR',

    UPDATE_OBJECT = 'UPDATE_OBJECT',
    UPDATE_OBJECT_FINISHED = 'UPDATE_OBJECT_FINISHED',
    UPDATE_OBJECT_ERROR = 'UPDATE_OBJECT_ERROR',

    DELETE_OBJECT = 'DELETE_OBJECT',
    DELETE_OBJECT_FINISHED = 'DELETE_OBJECT_FINISHED',
    DELETE_OBJECT_ERROR = 'DELETE_OBJECT_ERROR'

}
