export enum DashboardAction {

    DASHBOARD_INITIALIZE = "DASHBOARD_INITIALIZE",

    DASHBOARD_LOAD_CONTAINER_CONFIG = "DASHBOARD_LOAD_CONTAINER_CONFIG",

    DASHBOARD_CONTAINER_CONFIGURATION_LOADED = "DASHBOARD_CONTAINER_CONFIGURATION_LOADED"

}
