export enum CustomerEvent {

    LOAD_CUSTOMERS = 'LOAD_CUSTOMERS',
    CUSTOMERS_LOADED = 'CUSTOMERS_LOADED',

    CREATE_CUSTOMER = 'CREATE_CUSTOMER',
    CREATE_CUSTOMER_FINISHED = 'CREATE_CUSTOMER_FINISHED',
    CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR'

}
