export enum NotesEvent {

    LOAD_NOTES = 'LOAD_NOTES',
    NOTES_LOADED = 'NOTES_LOADED',

    SAVE_NOTES = 'SAVE_NOTES',
    SAVE_NOTES_FINISHED = 'SAVE_NOTES_FINISHED',
    SAVE_NOTES_ERROR = 'SAVE_NOTES_ERROR'

}
