export enum TicketCreationProcessAction {

    INITIALIZE = 'INITIALIZE',

    CREATE_TICKET = 'CREATE_TICKET',

    RESET_TICKET_CREATION = 'RESET_TICKET_CREATION',

    LOAD_TICKET_STATES = 'LOAD_TICKET_STATES',

    TICKET_DATA_LOADED = 'TICKET_STATES_LOADED'
}
